name: ESP-IDF Build and Release

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git
        cd esp-idf
        ./install.sh
        . ./export.sh

    - name: Install ADF
      run: |
        git clone --recursive https://github.com/espressif/esp-adf.git
        cd esp-adf
        . ./install.sh

    - name: Build project
      run: |
        . $HOME/esp/esp-idf/export.sh
        idf.py build

    - name: Generate version tag
      id: version
      run: echo "::set-output name=version::$(date +'%Y.%m.%d-%H%M%S')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/your-project-name.bin
        asset_name: your-project-name-${{ steps.version.outputs.version }}.bin
        asset_content_type: application/octet-stream