name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ESP-IDF dependencies
        run: |
          sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0

      - name: Clone ESP-IDF
        run: |
          git clone --recursive https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh

      - name: Clone ESP-ADF
        run: |
          git clone --recursive https://github.com/espressif/esp-adf.git
          cd esp-adf
          git submodule update --init --recursive

      - name: Set environment variables
        run: |
          echo "ADF_PATH=$(pwd)/esp-adf" >> $GITHUB_ENV
          echo "IDF_PATH=$(pwd)/esp-idf" >> $GITHUB_ENV

      - name: Build project
        run: |
          . ${{ env.IDF_PATH }}/export.sh
          idf.py build

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/*.bin
          retention-days: 1
