name: Build ESP32 Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake git

      - name: Install ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: latest
          target: esp32

      - name: Build firmware
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload firmware to releases
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: build/Toy_with_ble.bin